In [61]:
import numpy as np
import pandas as pd

In [62]:
index=['1','2','3']
data =["Ram","shyam","Dev"]
dic={1:"Tushar",2:"Dev",3:"Yash"}

In [63]:
pd.Series(data,index)

1      Ram
2    shyam
3      Dev
dtype: object

In [64]:
pd.Series(dic)

1    Tushar
2       Dev
3      Yash
dtype: object

In [65]:
# DAta Frame

In [66]:
data={
    "Name":["Tushar","Dev","Yash","krish"],
    "Age":[20,16,13,10],
    "Salary":[50000,30000,20000,15000],
    "post":["AI Engineer","Software Engg","Bro","small bro"]
}
df=pd.DataFrame(data,index=[1,2,3,4])
df

     Name  Age  Salary           post
1  Tushar   20   50000    AI Engineer
2     Dev   16   30000  Software Engg
3    Yash   13   20000            Bro
4   krish   10   15000      small bro

In [67]:
#   Selection column

In [68]:
df[["Name","Salary"]]

     Name  Salary
1  Tushar   50000
2     Dev   30000
3    Yash   20000
4   krish   15000

In [69]:
# create new column

In [70]:
df["city"]=["Mathura","Aring","Mathura","Aring"]

In [71]:
df

     Name  Age  Salary           post     city
1  Tushar   20   50000    AI Engineer  Mathura
2     Dev   16   30000  Software Engg    Aring
3    Yash   13   20000            Bro  Mathura
4   krish   10   15000      small bro    Aring

In [72]:
#  Drop column and rpow

In [73]:
df.drop(["city","post"],axis=1)

     Name  Age  Salary
1  Tushar   20   50000
2     Dev   16   30000
3    Yash   13   20000
4   krish   10   15000

In [74]:
df

     Name  Age  Salary           post     city
1  Tushar   20   50000    AI Engineer  Mathura
2     Dev   16   30000  Software Engg    Aring
3    Yash   13   20000            Bro  Mathura
4   krish   10   15000      small bro    Aring

In [75]:
df.drop([1,2],axis=0)

    Name  Age  Salary       post     city
3   Yash   13   20000        Bro  Mathura
4  krish   10   15000  small bro    Aring

In [76]:
# Selecting rows

In [77]:
df.loc[[1,2]]

     Name  Age  Salary           post     city
1  Tushar   20   50000    AI Engineer  Mathura
2     Dev   16   30000  Software Engg    Aring

In [78]:
df

     Name  Age  Salary           post     city
1  Tushar   20   50000    AI Engineer  Mathura
2     Dev   16   30000  Software Engg    Aring
3    Yash   13   20000            Bro  Mathura
4   krish   10   15000      small bro    Aring

In [79]:
df.iloc[2]

Name         Yash
Age            13
Salary      20000
post          Bro
city      Mathura
Name: 3, dtype: object

In [80]:
df.loc[[1,2]][["Name","Salary"]]

     Name  Salary
1  Tushar   50000
2     Dev   30000

In [81]:
df.loc[[3,4]][["Name","Age"]]

    Name  Age
3   Yash   13
4  krish   10

In [82]:
df[df["Age"]>10]

     Name  Age  Salary           post     city
1  Tushar   20   50000    AI Engineer  Mathura
2     Dev   16   30000  Software Engg    Aring
3    Yash   13   20000            Bro  Mathura

In [83]:
df[df["city"]=="Mathura"]

     Name  Age  Salary         post     city
1  Tushar   20   50000  AI Engineer  Mathura
3    Yash   13   20000          Bro  Mathura

In [84]:
df[(df["Age"]>10) & (df["city"]=="Mathura")]

     Name  Age  Salary         post     city
1  Tushar   20   50000  AI Engineer  Mathura
3    Yash   13   20000          Bro  Mathura

In [85]:
#  Missing data Na value

In [86]:
data={
    "A":[1,2,3,4],
   "B": [1,2,np.nan,3],
    "C":[2,np.nan,1,np.nan],
    "D":[1,2,3,np.nan]
    
}
df=pd.DataFrame(data)
df

   A    B    C    D
0  1  1.0  2.0  1.0
1  2  2.0  NaN  2.0
2  3  NaN  1.0  3.0
3  4  3.0  NaN  NaN

In [87]:
pd.isna(df)

       A      B      C      D
0  False  False  False  False
1  False  False   True  False
2  False   True  False  False
3  False  False   True   True

In [88]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False   True  False
2  False   True  False  False
3  False  False   True   True

In [89]:
df

   A    B    C    D
0  1  1.0  2.0  1.0
1  2  2.0  NaN  2.0
2  3  NaN  1.0  3.0
3  4  3.0  NaN  NaN

In [90]:
df.isna().sum()

A    0
B    1
C    2
D    1
dtype: int64

In [91]:
df.dropna()

   A    B    C    D
0  1  1.0  2.0  1.0

In [92]:
df.dropna(thresh=3)

   A    B    C    D
0  1  1.0  2.0  1.0
1  2  2.0  NaN  2.0
2  3  NaN  1.0  3.0

In [93]:
df.fillna(0)

   A    B    C    D
0  1  1.0  2.0  1.0
1  2  2.0  0.0  2.0
2  3  0.0  1.0  3.0
3  4  3.0  0.0  0.0

In [94]:
value={"A":100,"B":200,"C":300,"D":400}
df.fillna(value)

   A      B      C      D
0  1    1.0    2.0    1.0
1  2    2.0  300.0    2.0
2  3  200.0    1.0    3.0
3  4    3.0  300.0  400.0

In [95]:
df.fillna(df.mean())

   A    B    C    D
0  1  1.0  2.0  1.0
1  2  2.0  1.5  2.0
2  3  2.0  1.0  3.0
3  4  3.0  1.5  2.0

In [96]:
# Merging in two dataframe

In [97]:
data1 = {
    "EmpID": [101, 102, 103, 104, 105],
    "Name": ["Amit", "Priya", "Raj", "Simran", "Karan"],
    "Department": ["HR", "IT", "Finance", "Admin", None]
    
}
df1=pd.DataFrame(data1)
df1

   EmpID    Name Department
0    101    Amit         HR
1    102   Priya         IT
2    103     Raj    Finance
3    104  Simran      Admin
4    105   Karan       None

In [98]:
data2={
    "EmpID": [101, 102, 103, 106, 107],
    "Salary": [50000, 60000, None, 55000, 45000],
    "Location": ["Delhi", "Noida", "Pune", "Mumbai", "Chennai"]
}
df2=pd.DataFrame(data2)
df2

   EmpID   Salary Location
0    101  50000.0    Delhi
1    102  60000.0    Noida
2    103      NaN     Pune
3    106  55000.0   Mumbai
4    107  45000.0  Chennai

In [99]:
df=pd.merge(df1,df2,on="EmpID",how='outer')
df

   EmpID    Name Department   Salary Location
0    101    Amit         HR  50000.0    Delhi
1    102   Priya         IT  60000.0    Noida
2    103     Raj    Finance      NaN     Pune
3    104  Simran      Admin      NaN      NaN
4    105   Karan       None      NaN      NaN
5    106     NaN        NaN  55000.0   Mumbai
6    107     NaN        NaN  45000.0  Chennai

In [100]:
data = {
    "SaleID": [1,2,3,4,5,6,7,8,9,10,
               11,12,13,14,15,16,17,18,19,20],
    "Date": pd.date_range(start="2025-01-01", periods=20, freq="D"),
    "CustomerName": ["Neha","Meera","Meera","Ravi","Ravi","Suresh","Neha","Amit","Meera","Priya",
                     "Ravi","Amit","Meera","Neha","Priya","Suresh","Meera","Ravi","Amit","Priya"],
    "Product": ["Smartwatch","Smartwatch","Laptop","Tablet","Headphones","Mobile","Laptop","Tablet","Mobile","Smartwatch",
                "Charger","Laptop","Charger","Headphones","Smartwatch","Charger","Mobile","Laptop","Tablet","Headphones"],
    "Quantity": [3,4,1,3,3,2,1,4,2,3,4,2,3,1,2,3,1,4,2,4],
    "Price": [2185,1269,2933,5811,38319,46923,21744,42423,18687,17768,
              32365,43390,19252,47225,41581,40366,19236,16959,26095,24750]
}

In [101]:
df=pd.DataFrame(data)
df

    SaleID       Date CustomerName     Product  Quantity  Price
0        1 2025-01-01         Neha  Smartwatch         3   2185
1        2 2025-01-02        Meera  Smartwatch         4   1269
2        3 2025-01-03        Meera      Laptop         1   2933
3        4 2025-01-04         Ravi      Tablet         3   5811
4        5 2025-01-05         Ravi  Headphones         3  38319
5        6 2025-01-06       Suresh      Mobile         2  46923
6        7 2025-01-07         Neha      Laptop         1  21744
7        8 2025-01-08         Amit      Tablet         4  42423
8        9 2025-01-09        Meera      Mobile         2  18687
9       10 2025-01-10        Priya  Smartwatch         3  17768
10      11 2025-01-11         Ravi     Charger         4  32365
11      12 2025-01-12         Amit      Laptop         2  43390
12      13 2025-01-13        Meera     Charger         3  19252
13      14 2025-01-14         Neha  Headphones         1  47225
14      15 2025-01-15        Priya  Smartwatch         2  41581
15      16 2025-01-16       Suresh     Charger         3  40366
16      17 2025-01-17        Meera      Mobile         1  19236
17      18 2025-01-18         Ravi      Laptop         4  16959
18      19 2025-01-19         Amit      Tablet         2  26095
19      20 2025-01-20        Priya  Headphones         4  24750

In [102]:
df.groupby(["CustomerName","Product"])["Price"].sum()

CustomerName  Product
Amit          Laptop        43390
              Tablet        68518
Meera         Charger       19252
              Laptop         2933
              Mobile        37923
              Smartwatch     1269
Neha          Headphones    47225
              Laptop        21744
              Smartwatch     2185
Priya         Headphones    24750
              Smartwatch    59349
Ravi          Charger       32365
              Headphones    38319
              Laptop        16959
              Tablet         5811
Suresh        Charger       40366
              Mobile        46923
Name: Price, dtype: int64

In [103]:
# Aggregation

In [104]:
df[("Price")].agg(['mean','median','min','max'])

mean      25464.05
median    23247.00
min        1269.00
max       47225.00
Name: Price, dtype: float64

In [105]:
#pivot_tables and crosstab

In [106]:
#  operations

In [107]:
df=pd.DataFrame(
    {
        'A':[1,2,3,4,5],
        'B':[10,20,30,40,50],
        'C':[100,200,300,400,500]
    }
)
df

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [108]:
df.shape

(5, 3)

In [109]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [110]:
df.info

<bound method DataFrame.info of    A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500>

In [111]:
df.describe

<bound method NDFrame.describe of    A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500>

In [112]:
def square(x):
    return x**2

In [113]:
df['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [115]:
df['C'].apply(lambda x:x**2)

0     10000
1     40000
2     90000
3    160000
4    250000
Name: C, dtype: int64